services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "1234@password"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql

  web:
    build:
      context: ./dj
      dockerfile: Dockerfile
    volumes:
      - ./dj:/code
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "mssql://sa:1234@password@db:1433/dj-project"
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mssql-data: