version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "1234@password"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql

  web:
    image: django:latest
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./dj:/code
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "mssql://sa:1234@password@db:1433/dj-project"
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mssql-data: